{% set version = "1.7.0" %}

package:
  name: scikit-rf
  version: {{ version }}


source:
  fn: scikit-rf-{{ version }}.zip
  url: https://github.com/scikit-rf/scikit-rf/archive/v{{ version }}.zip
  sha256: a03bb30d3d4f54aee1d0a45618c89c7d6d7b47ec66cf7d66a2f80c1da3e22cab



build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas
    - ipython
    - numpy
    - scipy
    - matplotlib-base
    - six
    - future
    - qtpy
    - pyyaml
    - pyqtgraph
    - pyvisa
    - sip
    - traits
    - bokeh
    - traitsui

test:
  requires:
    - python {{ python_min }}
  imports:
    - skrf
    - skrf.calibration
    - skrf.data
    - skrf.io
    - skrf.media

about:
  home: http://www.scikit-rf.org
  license: BSD-3-Clause
  summary: Object Oriented Microwave Engineering.
  doc_url: http://scikit-rf.readthedocs.io/
  dev_url: https://github.com/scikit-rf/scikit-rf
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - arsenovic
    - jhillairet
